image: python:alpine

before_script:
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install mkdocs-awesome-pages-plugin
  - pip install pymdown-extensions
  - pip install markdown-blockdiag
  - pip install markdown-include
  - pip install mkdocs-pdf-export-plugin

pages:
  script:
  - mkdocs build --clean
  - mv site public
  artifacts:
    paths:
    - public
  only:
  - master
