# Informations sur le projet
site_name: WikiFoncier
site_description: 'Une expérimentation pour un usage sobre et efficace du foncier par le partage de ressources'
site_url: 'https://know-rmandie.gitlab.io/Collectif-Foncier'
#site_url: 'http://127.0.0.1:8000'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Collectif Foncier'

# Dépôt
repo_name: 'know-rmandie/Collectif-Foncier'
repo_url: 'https://gitlab.com/know-rmandie/Collectif-Foncier/'
edit_uri: 'edit/contributions/docs'
new_uri: 'new/contributions/docs'

# Configuration Personalisation
theme:
  name: material
  custom_dir: theme
  language: fr
  font: false
  feature:
    tabs: true
  palette:
    primary: 'deeppurple'
    accent: 'amber'

extra_css:
  - ext/style.css

# Plugins
plugins:
  - search:
      language: 'fr, en'
  - awesome-pages
#  - git-revision-date

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: flow
        - class: uml-flowchart
        - format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"
