# Informations sur le projet
site_name: Collectif Foncier
site_description: 'Une expérimentation pour un usage sobre et efficace du foncier par le partage de ressources'
site_url: 'https://know-rmandie.gitlab.io/Collectif-Foncier'

# Copyright
copyright: 'Copyright &copy; 2019 - 2020 Collectif Foncier'

# Dépôt
repo_name: 'know-rmandie/Collectif-Foncier'
repo_url: 'https://gitlab.com/know-rmandie/Collectif-Foncier/'
edit_uri: 'edit/contributions/docs'

# Configuration Personalisation
theme:
  name: material
  custom_dir: theme
  language: fr
  font: false
  feature:
    tabs: true
  palette:
    primary: 'cyan'
    accent: 'amber'

extra_css:
  - '../theme/style.css'

# Plugins
plugins:
  - search
  - awesome-pages

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: "#"
