name: Publication

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout on Current Commit
      uses: actions/checkout@master
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
        architecture: 'x64'
    - name: Install requirements
      run: python -m pip install -r py-requirements.txt
    - name: Build with mkdocs
      run: python -m mkdocs build --clean
    - name: Say that this is not Jekyll
      run: cat > site/.nojekyll
    - name: Publish site
      uses: maxheld83/ghpages@v0.2.1
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: ./site/
